# Generated by Django 2.2.1 on 2019-06-23 20:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('matricula', models.CharField(max_length=15, verbose_name='Matrícula')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo')),
                ('carga_horaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)], verbose_name='Carga Horária')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('foto', models.ImageField(upload_to='cursos', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Areas')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('inscritos', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('publicos', models.ManyToManyField(to='core.Publicos')),
            ],
        ),
    ]
